import * as fs from "node:fs";
import * as path from "node:path";
import { defaultMarkerRules } from "./rules.js";
import { toClaudeCodeSettings } from "./adapters.js";

/**
 * Find the consuming repo's root by walking up from cwd looking for package.json.
 */
export function findRepoRoot(startDir: string = process.cwd()): string {
  let dir = path.resolve(startDir);
  while (dir !== path.dirname(dir)) {
    if (fs.existsSync(path.join(dir, "package.json"))) {
      return dir;
    }
    dir = path.dirname(dir);
  }
  throw new Error("Could not find repo root (no package.json found in parent directories)");
}

/**
 * Generate and install Marker hook scripts in a consuming repo.
 */
export function install(targetDir?: string): void {
  const repoRoot = targetDir ?? findRepoRoot();

  // 1. Create .marker/hooks/ directory
  const markerDir = path.join(repoRoot, ".marker");
  const hooksDir = path.join(markerDir, "hooks");
  fs.mkdirSync(hooksDir, { recursive: true });

  // 2. Write hook shell scripts
  // Use node with absolute path to the compiled CLI — these are installed via file: dependency
  // so they live at node_modules/@marker/hooks/dist/handlers/*.js
  const hooksPackageDir = path.join(repoRoot, "node_modules", "@marker", "hooks");
  const preCliPath = path.join(hooksPackageDir, "dist", "handlers", "pretooluse-cli.js");
  const postCliPath = path.join(hooksPackageDir, "dist", "handlers", "posttooluse-cli.js");

  const preToolUseScript = `#!/bin/bash
# Marker PreToolUse hook — invokes compiled handler via node
# Auto-generated by @marker/hooks — do not edit manually
exec node "${preCliPath}"
`;

  const postToolUseScript = `#!/bin/bash
# Marker PostToolUse hook — invokes compiled handler via node
# Auto-generated by @marker/hooks — do not edit manually
exec node "${postCliPath}"
`;

  fs.writeFileSync(path.join(hooksDir, "pretooluse.sh"), preToolUseScript, { mode: 0o755 });
  fs.writeFileSync(path.join(hooksDir, "posttooluse.sh"), postToolUseScript, { mode: 0o755 });

  // 3. Write .claude/settings.json
  const claudeDir = path.join(repoRoot, ".claude");
  fs.mkdirSync(claudeDir, { recursive: true });

  const absoluteHooksDir = path.resolve(repoRoot, ".marker", "hooks");
  const settings = toClaudeCodeSettings(defaultMarkerRules, absoluteHooksDir);
  fs.writeFileSync(
    path.join(claudeDir, "settings.json"),
    JSON.stringify(settings, null, 2) + "\n",
    "utf-8",
  );

  // 4. Add .marker/ to .gitignore if not already there
  const gitignorePath = path.join(repoRoot, ".gitignore");
  if (fs.existsSync(gitignorePath)) {
    const content = fs.readFileSync(gitignorePath, "utf-8");
    if (!content.includes(".marker/")) {
      fs.appendFileSync(gitignorePath, "\n# Marker agent hooks (local, not committed)\n.marker/\n");
    }
  } else {
    fs.writeFileSync(gitignorePath, "# Marker agent hooks (local, not committed)\n.marker/\n");
  }

  // 5. Write editable config file
  const configContent = `// Marker hooks configuration — edit to override default rules.
// This file is local to your repo and not committed to git.
import { defaultMarkerRules, type HookRules } from "@marker/hooks";

export const rules: HookRules = {
  ...defaultMarkerRules,
  // Override specific rules here, e.g.:
  // protectedPaths: [...defaultMarkerRules.protectedPaths, "my-custom-path.ts"],
};
`;
  const configPath = path.join(markerDir, "config.ts");
  if (!fs.existsSync(configPath)) {
    fs.writeFileSync(configPath, configContent, "utf-8");
  }

  console.log(`[marker-hooks] Installed hooks in ${repoRoot}`);
  console.log(`  - .marker/hooks/pretooluse.sh`);
  console.log(`  - .marker/hooks/posttooluse.sh`);
  console.log(`  - .claude/settings.json`);
  console.log(`  - .marker/config.ts (editable)`);
}
